In [1]:
print("mak ka bhosda aaaaggg")

mak ka bhosda aaaaggg


In [4]:
st="amitabbacchan"
na="iski ma ko natu"
print(st.upper())
print(na.upper())
print(len(st))
print(st[::-1])

AMITABBACCHAN
ISKI MA KO NATU
13
nahccabbatima


In [15]:
x="welcomne.to,vedam,for,learning.machine.learning"
x.replace(",","?").replace(".",",").replace("?",".")




'welcomne,to.vedam.for.learning,machine,learning'

In [ ]:
sc="charlie-bravo-alpha"
print(sc.replace("-"," ").upper()[::-1])

AHPLA OVARB EILRAHC


In [ ]:
##question 1
name=" rahul KUMAR sharma"
name=(name.split())
if "".join(name).isalpha():
    name=" ".join(name).lower().title()
    print(name)
else:
    print("Name is not valid")




Rahul Kumar Sharma


In [23]:
##question 2
Str=" 45, 67, 89, 23, 12, 90"
Str="".join(Str.split())
ls=list(map(int,Str.split(",")))
ans=sum(ls)
print(ls)
print(ans//len(ls))

[45, 67, 89, 23, 12, 90]
54


In [24]:
some_dic={x: x**x for x in range(1,11)}
print(some_dic)


{1: 1, 2: 4, 3: 27, 4: 256, 5: 3125, 6: 46656, 7: 823543, 8: 16777216, 9: 387420489, 10: 10000000000}


In [2]:
import numpy as np

In [1]:
!pip install numpy

In [3]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
x=np.array([1,2,3,4,5])
print(x,type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.full((3,3),7))


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [11]:
print(np.arange(1,13).reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
print(np.eye(5,10))
print(np.eye(5,10,k=3))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
