In [2]:
import numpy as np


In [3]:
print(np.eye(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
x=np.array([1,2,3,4,5])
print(x,type(x))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
print(np.ones((3,3)))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.full((3,3),7))


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
print(np.arange(1,13).reshape(4,3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(np.eye(5,10))
print(np.eye(5,10,k=3))


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
