In [2]:
import numpy as np


In [3]:
print(np.eye(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
x=np.array([1,2,3,4,5])
print(x,type(x))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
print(np.ones((3,3)))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.full((3,3),7))


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
print(np.arange(1,13).reshape(4,3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(np.eye(5,10))
print(np.eye(5,10,k=3))


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [11]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.full((3,3),0))
print(np.full((3,3),1))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
print(np.arange(2,21,2))

[ 2  4  6  8 10 12 14 16 18 20]


In [15]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr=np.eye(4,4)
print(arr)
print(np.size(arr))
print(np.shape(arr))
print(arr.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
16
(4, 4)
2


In [22]:
arr=np.arange(1,6)
arr=arr.astype(float)
print(type(arr))

<class 'numpy.ndarray'>


In [24]:
s=np.arange(0,20).reshape(5,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [43]:
sli=s[1:3,0:3]
print(sli)

[[ 4  5  6]
 [ 8  9 10]]
