In [1]:
import numpy as np


In [4]:
A=np.array([1,2.5,"Hello"])
print(A)
print(A.dtype)

['1' '2.5' 'Hello']
<U32


In [5]:
A=np.array([1,2.5,3.5])
print(A)
print(A.dtype)

[1.  2.5 3.5]
float64


In [6]:
A=np.array([1,2.5,3.5],dtype=int)
print(A)
print(A.dtype)

[1 2 3]
int64


In [8]:
A=np.array([1,2.5,3.5])
print(A)
A.astype('int32')

[1.  2.5 3.5]


array([1, 2, 3], dtype=int32)

In [14]:
X=np.arange(0,20).reshape(5,4)
print(X)
print("main",X[1:2,1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
main [[5 6 7]]


rivison till now


In [3]:
import numpy as np



In [ ]:
arr1=np.arange(10)
print(arr1)
arr1=arr1+5
print(arr1)
print("Multiply",arr1*2)
print("exponent",arr1**2)


[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
Multiply [10 12 14 16 18 20 22 24 26 28]
exponent [ 25  36  49  64  81 100 121 144 169 196]
exponent [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06]


In [26]:
arr1=np.arange(10)
arr2=np.arange(10,20)
# length should be same for both arrays to perform addition
print(arr1,arr2)
print(arr1+arr2)
d1=np.arange(10).reshape(2,5)
d2=np.arange(10,20 ).reshape(2,5)
print(d1,d2)
print(d1+d2) # this will give error because the shape of both arrays is different

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[[0 1 2 3 4]
 [5 6 7 8 9]] [[10 11 12 13 14]
 [15 16 17 18 19]]
[[10 12 14 16 18]
 [20 22 24 26 28]]


In [29]:
x=np.arange(10).reshape(2,5)
y=np.arange(10,20).reshape(2,5)
print(x)
print(y)
print(x==y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[False False False False False]
 [False False False False False]]


In [39]:
# UNIFORM DISTRIBUTION
# np.random.rand() generates a random number between 0 and 1. It can also generate an array of random numbers if you specify the shape.
# np.random.seed() is used to set the seed for the random number generator. This ensures that the random numbers generated are reproducible. If you set the same seed, you will get the same random numbers every time you run the code.
# NORMAL DISTRIBUTION
# np.random.randn() generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). It can also generate an array of random numbers if you specify the shape.
print(np.random.seed(5))
print(np.random.rand(10))
print(np.random.seed(5))
print(np.random.randn(10))

None
[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386
 0.76590786 0.51841799 0.2968005  0.18772123]
None
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984  1.58248112
 -0.9092324  -0.59163666  0.18760323 -0.32986996]


In [ ]:
# np.random.randint() generates random integers between a specified range. It can also generate an array of random integers if you specify the shape.
# np.random.randint(low=0, high=10, size=(5,3))
print(np.random.randint(0,10,(5,3)))

[[9 3 2]
 [4 6 9]
 [3 3 2]
 [1 5 7]
 [4 3 1]]


In [102]:
# np.random.choice() generates a random sample from a given 1-D array. It can also generate an array of random samples if you specify the shape.
# np.random.shuffle() randomly shuffles the elements of a given array in place. It does not return a new array, but modifies the original array.
lst=[1,2,3,4,5]
# np.random.choice(lst, size=3, replace=False,probability) # replace=False means that the same element cannot be selected more than once
print(np.random.choice(lst,3,replace=True, p=[0.1, 0.2, 0.3, 0.2, 0.2])) # replace=True means that the same element can be selected more than once
print(np.random.choice(lst,3,replace=False)) # replace=False means that the same element cannot be selected more than once
np.random.shuffle(lst)
print(lst)

[4 4 4]
[3 2 4]
[1, 3, 4, 2, 5]


In [112]:
# min max mean std median sum are some of the statistical functions that can be performed on an array. These functions can be used to get a better understanding of the data and its distribution.
x=np.arange(35,100).reshape(5,13)
print(x)
print(np.mean(x))
print(np.max(x))
print(x.min(axis=0))
print(np.std(x))
print(np.median(x))
print(np.sum(x))
# for perticular row and columb
print(np.mean(x,axis=1)) # axis=0 means that the function will be applied to each column

[[35 36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70 71 72 73]
 [74 75 76 77 78 79 80 81 82 83 84 85 86]
 [87 88 89 90 91 92 93 94 95 96 97 98 99]]
67.0
99
[35 36 37 38 39 40 41 42 43 44 45 46 47]
18.76166303929372
67.0
4355
[41. 54. 67. 80. 93.]
