In [1]:
import numpy as np

In [ ]:
# Q1
np.random.seed(42)
x=np.random.randint(1,7,10)
print(x)


[4 5 3 5 5 2 3 3 3 5]


In [19]:
#Q2
x=np.random.randint(35,100,20)
print(x)
print(np.mean(x))
print(np.max(x))
print(np.min(x))
print(np.std(x))

[74 87 58 60 94 75 63 49 79 99 43 35 42 97 45 42 69 69 67 39]
64.3
99
35
19.69796943849797


In [ ]:
#Q3
X = np.random.randint(10, 51, 12).reshape(3, 4)
print(X)

[[48 50 37 16]
 [18 17 21 43]
 [42 32 33 46]]


In [ ]:
#Q4
